[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportUnknownMemberType = true

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.ruff]
select = ["E" , "F" , "B" , "I"]
line-length = 100